[extension]
name = "pguint"
version = "0.0.0"
repository = "https://github.com/petere/pguint"
license = "PostgreSQL"
description = "Unsigned integer types extension for PostgreSQL."
documentation = "https://github.com/petere/pguint"
categories = ["data_transformations"]

[build]
postgres_version = "15"
platform = "linux/amd64"
dockerfile = "Dockerfile"
install_command = """
    cd pguint && make install
    set -x
    mv /usr/local/pgsql/share/extension/* /usr/share/postgresql/15/extension
    mv /usr/local/pgsql/lib/* /usr/lib/postgresql/15/lib
    """
